### ISSUE TITLE
Tuple named fields are placed in surrounding scope causing redefinition errors

### ISSUE THREAD

**Issue by nmtiwari** [boalang/compiler#103]
````
type foo = {a: float, b: float};
type bar = {a:float, c: float}; # a has already been created
````

**Comment by psybers** [comment]
This is a bigger problem than 2 tuples.  The tuple fields are being placed into the surrounding scope.  So you can't even make a variable named `a`.

**Comment by psybers** [comment]
Also, again, what branch is this on?  Because your exact test case actually has no type error.  It just gives codegen errors.
