### ISSUE TITLE
Project metadata does not indicate fork, number of forks, stars, watchers

### ISSUE THREAD

**Issue by psybers** [boalang/compiler#105]
On systems like Git, you can fork a repository/project.  The metadata should indicate if the project is or is not a fork.  This is useful for filtering projects.

**Comment by RobertHSchmidt** [comment]
The metaData has a boolean "fork" true if the repo is a fork, "forks_count" number of forks, "stargazers_count" number of stars. It had "watchers" and "watchers_count" but both fields match the stargazers count not the number of watchers. Let me know if there is any other data you feel should be included.

**Comment by nguyenhoan** [comment]
Those fields are there and the protobuf is ready for it but those fields are not set yet.
Please do that.

Please also add the default_branch

**Comment by nguyenhoan** [comment]
https://github.com/boalang/compiler/commit/d3c53f364004b2219aa3441be9a1658878f34d69
