### ISSUE TITLE
Do not treat renamed files as modified

### ISSUE THREAD

**Issue by nguyenhoan** [boalang/compiler#117]
Since only the new path is stored, the old path is lost.
Function getsnapshot(..) includes old paths of renamed files in the result.

**Comment by psybers** [comment]
Was this fixed, and if so what commit?

**Comment by nguyenhoan** [comment]
https://github.com/boalang/compiler/commit/1a683294b6d9693b7e5234d4a67566d2a51e48a7#diff-b5b8b9eea63325aa6440932e86e649d9R126

**Comment by psybers** [comment]
Does getsnapshot() require updates for this change?

**Comment by nguyenhoan** [comment]
Yes. We have another issue for that #135
