### ISSUE TITLE
Add data generation support for JavaScript code.

### ISSUE THREAD

**Issue by psybers** [boalang/compiler#126]
Most likely based off JSDT:
http://help.eclipse.org/kepler/index.jsp?topic=%2Forg.eclipse.wst.jsdt.doc%2Freference%2Fapi%2Forg%2Feclipse%2Fwst%2Fjsdt%2Fcore%2Fdom%2Fpackage-tree.html

**Comment by RobertHSchmidt** [comment]
Jsdt..core.dom.ast only has JSL2 and JSL3, it looks like jsl3 supports unto ECMAScript4.

**Comment by RobertHSchmidt** [comment]
It looks like eclipse is rebooting JSDT to extend support to EMCASript6, by using ESPIRMA as the background parser. https://projects.eclipse.org/proposals/esprima

**Comment by psybers** [comment]
So then the question is, do we do similar?  Java has a ECMAScript engine, so we could actually directly call the ESPRIMA parser and then convert the resulting tree.

**Comment by nguyenhoan** [comment]
I found this works
https://stackoverflow.com/questions/6511556/javascript-parser-for-java

but it seems to parse only function instead of entire program.

The Java script engine seems to execute the JS code instead of parsing it. I might have missed something.

**Comment by nguyenhoan** [comment]
Just for archive
http://esprima.readthedocs.io/en/4.0/syntax-tree-format.html

**Comment by nguyenhoan** [comment]
Mozilla Rrhino is good choice too.
This post has a complete example of parsing and visiting
http://ramkulkarni.com/blog/parsing-javascript-code-using-mozilla-rhino/

**Comment by psybers** [comment]
I meant we can run the JS parser ESPRIMA (written in JS) using the Java ECMA script engine.  So it will execute ESPRIMA, and we will feed in the source to that call (as a JS string).

**Comment by psybers** [comment]
https://github.com/mozilla/rhino

**Comment by doubleblinddoubleblind** [comment]
I vote for Mozilla Rhino

**Comment by nguyenhoan** [comment]
I vote for Mozilla Rhino

**Comment by RobertHSchmidt** [comment]
Rhino parser treats FuntionNode, VariableDeclaration and KeyWordLiteral Nodes at times as expressions and at times as statements. I am using checks wherever I expect statements as well as some checks in FunctionNode and VariableDeclaration visit methods.

**Comment by RobertHSchmidt** [comment]
Should ObjectLiteral be treated as a class?

**Comment by nguyenhoan** [comment]
I found this quite useful
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference

**Comment by psybers** [comment]
Mapping of JS AST to the Boa AST:
https://docs.google.com/document/d/1zbyGvdEFASAogtdhiV_eZrXPSXdVHecx9IYgyueLJpw/edit?usp=sharing

**Comment by nguyenhoan** [comment]
@RobertHSchmidt could you add test cases for all AST nodes in JS which have different syntax or semantics with Java's.
