### ISSUE TITLE
Add Git branches to dataset

### ISSUE THREAD

**Issue by psybers** [boalang/compiler#127]
Git supports branches. We need to keep this data (list of branches and their associated commit hashes) in our dataset.

Our code currently has a getBranches() for Git, but it is never called anywhere. See:
https://github.com/boalang/compiler/blob/ee5a2fe5d966f9cdfcbdcefe3e6ac84d313f0855/src/java/boa/datagen/scm/GitConnector.java#L136

**Comment by nguyenhoan** [comment]
Using command line: git branch gives a list of branches and git rev-parse name gives the head of branch name.
However, the JGit API in getBranches() returns an empty list of branches.

I will check other APIs.

**Comment by nguyenhoan** [comment]
Both getBranches() and getTags() work. Need to pass the path all the way to the (.git) folder containing administrative files when creating the repository.

**Comment by nguyenhoan** [comment]
https://github.com/boalang/compiler/commit/a873dfabc22418a745ca3d4c6d93f2f1fa4454c6
