### ISSUE TITLE
Add data generation support for PHP code

### ISSUE THREAD

**Issue by nguyenhoan** [boalang/compiler#130]
Eclipse PDT is actively supporting PHP language versions
http://www.eclipse.org/pdt/articles/ast/PHP_AST.html

**Comment by RobertHSchmidt** [comment]
Php allows nested Namespaces should we add repeated namespaces to ast.proto?

**Comment by nguyenhoan** [comment]
Repeated nested namespaces were added.

**Comment by nguyenhoan** [comment]
@RobertHSchmidt could you add test cases for all AST nodes in PHP which have different syntax or semantics with Java's.

**Comment by RobertHSchmidt** [comment]
Testing against a large project HFO4/shudong-share found that we are still visiting identifier node, throwing visited unused node exception. ArrayAccess index can be an scalar or an identifier. I will fix and keep testing for other issues.

**Comment by RobertHSchmidt** [comment]
I am treating identifier as a literal.
