### ISSUE TITLE
Add recovery mechanism for repo cloner

### ISSUE THREAD

**Issue by nguyenhoan** [boalang/compiler#131]
I don't see a recovery mechanism for repo cloner yet.
Please keep in mind that the cloning could be run on different threads and processes and the storage could be on different hard disks.

Logging successfully cloned repos into files, a file for each thread, and storing all log files in a folder could be a solution.

**Comment by nguyenhoan** [comment]
No longer needed since git clone command already takes care of that.

**Comment by psybers** [comment]
Isn't this needed for non-Git repos?
