### ISSUE TITLE
Support Java AST diffs in dataset

### ISSUE THREAD

**Issue by psybers** [boalang/compiler#132]
The dataset should have a way to give the user a diff between 2 neighboring versions of a file.  Preferably this diff would be AST-based and not textual.

**Comment by nguyenhoan** [comment]
diff utility 
https://github.com/boalang/compiler/tree/datagen2017/src/java/boa/datagen/treed

add differencing information to Boa AST nodes
https://github.com/boalang/compiler/commit/f087d2d423b5e31280a939cd76a0755dc47aef9d
