### ISSUE TITLE
getsnapshot method include renamed files and files in different branches 

### ISSUE THREAD

**Issue by nguyenhoan** [boalang/compiler#135]
`1 --> 2 --> 5 --> 7`
`  |---> 3`
`  |----> 4 ---> 6`
(numbers are commit ids)

With this commit graph, snapshot at 7 will include all changed files from other branches where 3, 4 and 6 could modify files in 1,2,5,7 branch or even add new files.

**Comment by psybers** [comment]
For this to work, we need #127 implemented first.

**Comment by nguyenhoan** [comment]
With the added information about the parent commits, we can do this by walking backwards with knowing the branch.

**Comment by nguyenhoan** [comment]
A working version of getting a snapshot in data generation
https://github.com/boalang/compiler/blob/81fce10ca2b10c4407fe892d2f2798abd7df74ba/src/java/boa/datagen/scm/AbstractConnector.java#L120

**Comment by nguyenhoan** [comment]
@psybers could you please fix this one?

**Comment by nguyenhoan** [comment]
fixed at https://github.com/boalang/compiler/commit/be460490165034cdf23f868298e0649d333e0325
