### ISSUE TITLE
Add traceability from Boa results to the actual code to verify results

### ISSUE THREAD

**Issue by nguyenhoan** [boalang/compiler#141]
Given the project name, commit id and file path, it is straightforward to construct a link to the file on GitHub.

https://github.com/username/reponame/blob/commit id/file path
or 
https://github.com/username/reponame/commit/commit id/#diff-file path MD5

https://github.com/boalang/compiler/blob/7ea4d03a8275a4791bb7d36207ca93565f8aa5f7/README.md

https://github.com/boalang/compiler/commit/7ea4d03a8275a4791bb7d36207ca93565f8aa5f7#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by nguyenhoan** [comment]
Dr. Rajan's suggestion

> Perhaps we can fork each cloned project using a special Boa user at the point when we clone it. If we don't update our fork, we can point our URLs to our fork, right? If the original repository is deleted do forks go away too?

**Comment by RobertHSchmidt** [comment]
Deleting a public repository

When you delete a public repository, one of the existing public forks is chosen to be the new parent repository. All other repositories are forked off of this new parent and subsequent pull requests go to this new parent.
from https://help.github.com/articles/what-happens-to-forks-when-a-repository-is-deleted-or-changes-visibility/

**Comment by nguyenhoan** [comment]
Hi @RobertHSchmidt 

I saw that you call curl in a process created in Java to send a PATCH to rename a forked repo.
https://github.com/boalang/compiler/blob/c015c42f817070fa5e9a4eed85f80d6e82ffe53a/src/java/boa/datagen/util/Forker.java#L73

Is there any API to do that instead?
for example https://salesforce.stackexchange.com/questions/54870/working-example-of-update-using-patch-from-java-on-rest-api

**Comment by RobertHSchmidt** [comment]
GitHub flagged, The forking account. Need another way to maintain traceability.

**Comment by nguyenhoan** [comment]
We will go with the solution of referring to GitHub links
