### ISSUE TITLE
Keep content of textual, unparsed files to the dataset

### ISSUE THREAD

**Issue by nguyenhoan** [boalang/compiler#151]
Useful for tasks that processing contents as textual documents.
Users might also write simple parser in Boa to parse and extract information.

**Comment by nguyenhoan** [comment]
53daba467128975e36f9fc1628075d0c7ddc8c8c

**Comment by nguyenhoan** [comment]
I don't see benefit of storing parsed files because they are already in the asts.
Storing them would increase the space significantly.

**Comment by hridesh** [comment]
Agreed. Perhaps limit textual contents to unparsed ASCII files?

**Comment by psybers** [comment]
Parsed files do not retain all information (such as whitespace and comments) however.  Hence my thoughts to including them.
