### ISSUE TITLE
getsnapshot() consistency issue

### ISSUE THREAD

**Issue by psybers** [boalang/compiler#167]
Imagine a file such as `/foo.java` in the repository and the standard `getsnapshot(n, now(), "SOURCE_")` that filters to keep only files that parse without error.

* The first commit at time `T1` the file parsed without error.
* Later at time `T2`, the file was changed.  Now it has a parse error.
* Later at time `T3`, the file was removed.

If you call `getsnapshot()` we would expect the file to not be in the snapshot.  This seems to be handled properly at the moment.

However, if the change at `T3` did not occur, what do we expect about the file?

1. Do we get the parsed file from time `T1`?  The file at `T2` would be filtered as it has parse error.  **This is the current behavior.**
1. Do we get no file because the latest version didn't match the filters?  **I suspect we want this.**

Relevant code is here: https://github.com/boalang/compiler/blob/c19f9d5da032cf274d3ede889112eb6a6ef83579/src/java/boa/functions/BoaAstIntrinsics.java#L413-L432

**Comment by nguyenhoan** [comment]
Could there be the third behavior where the result indicate a file with that name should be there but cannot be parsed?

**Comment by psybers** [comment]
So that behavior would be leaving the file from time T2?  I don't think that is a possibility, because that file doesn't pass the filter(s) saying to only give us files that parsed.

I always viewed the behavior as 'give me all the code at time X, and then filter out anything not matching one of the filters.'

**Comment by nguyenhoan** [comment]
Why does getsnapshot() have to filter out unparseable files?
It should just simplely return all files at the given revision/commit.
Users could further filter the returned files as needed. If they want the most recent parseable version of a n unparseable file, they could also do that by tracking the history.

**Comment by psybers** [comment]
It doesn't have to.  But it has the ability to filter, and my point was if someone was filtering that is the case we are not handling properly at the moment.

**Comment by nguyenhoan** [comment]
okay. I get it now.
So I would go with the second behavior: no file.

**Comment by nguyenhoan** [comment]
I revised the getsnapshot functions to fix issue #135 
It also addresses this issue: behavior 2.

https://github.com/boalang/compiler/blob/master/src/java/boa/functions/BoaAstIntrinsics.java#L477-L479
https://github.com/boalang/compiler/blob/master/src/java/boa/functions/BoaAstIntrinsics.java#L484-L486
https://github.com/boalang/compiler/blob/master/src/java/boa/functions/BoaAstIntrinsics.java#L495-L497
https://github.com/boalang/compiler/blob/master/src/java/boa/functions/BoaAstIntrinsics.java#L511-L513https://github.com/boalang/compiler/blob/master/src/java/boa/functions/BoaAstIntrinsics.java#L522-L524

**Comment by nguyenhoan** [comment]
Not yet.
@RobertHSchmidt might be able to help with this.

**Comment by nguyenhoan** [comment]
I added the first test case using the above scenario 
https://github.com/boalang/compiler/commit/8e83df0eca42eb117f21b18685f017f2d34e08ec

**Comment by nguyenhoan** [comment]
Found a bug that almost all parseable Java source files now have JLS 8 because calling modifiers() on TypeDeclaration node throws unsupported operation exception for all earlier version.
https://github.com/boalang/compiler/blob/bdfb811b259ba40f5be8bf3ccea34a5030e63f20/src/java/boa/datagen/util/Java7Visitor.java#L230
