### ISSUE TITLE
Parseable Java source files are incorrectly assigned version of JLS

### ISSUE THREAD

**Issue by nguyenhoan** [boalang/compiler#188]
Almost all parseable Java source files now have JLS 8 because calling methods such as thrownExceptionTypes() on MethodDeclarationnode throws unsupported operation exception for all earlier versions.
https://github.com/boalang/compiler/blob/bdfb811b259ba40f5be8bf3ccea34a5030e63f20/src/java/boa/datagen/util/Java7Visitor.java#L801

JDT parser seems to skip some language features, e.g., binary literals and underscores in numeric literals, without marking it MALFORMED if parsing with earlier API level

**Comment by psybers** [comment]
The [JDT docs](https://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fdom%2FBodyDeclaration.html&anchor=modifiers--) seem to indicate it only throws for JLS2?

**Comment by nguyenhoan** [comment]
Sorry for posting the issue in a hurry.
I later realized that and updated the post with [`MethodDeclaration.thrownExceptionTypes()`](https://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fdom%2FBodyDeclaration.html&anchor=modifiers--)

[`NaiveASTFlattener`](https://github.com/boalang/eclipse.jdt.core/blob/master/org/eclipse/jdt/internal/core/dom/NaiveASTFlattener.java) should be used as guideline.

I will review the  visitor

**Comment by nguyenhoan** [comment]
Resolved #193
