### ISSUE TITLE
Recursive function does not work

### ISSUE THREAD

**Issue by rangeetpan** [boalang/compiler#242]
Executing a function where there is no return type in the recursive call. Similar to the skeleton code attached below
o: output sum of int;
f := function(i: int)  {
  if (i > 5)
   {
   }
   else
   {
     f(i + 1);
     o << 1;
   }
};
f(5);
The compiler throws error of not finding the recursive function.

**Comment by psybers** [comment]
And specifically - the test case you provided here compiles just fine for me using the master branch.
