### ISSUE TITLE
Boa Switch Statement

### ISSUE THREAD

**Issue by hyjorc1** [boalang/compiler#245]
https://github.com/boalang/compiler/blob/59ee09ab18a53d29641ef2839477f97421ab6a8e/src/java/boa/datagen/util/JavaVisitor.java#L1300-L1314

Should we use b.addConditions() instead of addExpresssions() for switch conditional expression? The prettyprint also used conditions atttibute for switch statement. If yes, can I change "expressions" to "conditions" under the SwtichCase.boa in order to pass the test.

https://github.com/boalang/compiler/blob/59ee09ab18a53d29641ef2839477f97421ab6a8e/test/datagen/boa/SwitchCase.boa#L1-L23

https://github.com/boalang/compiler/blob/59ee09ab18a53d29641ef2839477f97421ab6a8e/test/datagen/java/SwitchCase.java#L1-L3

**Comment by psybers** [comment]
No.  For `switch (e) { .. }` the `e` here is an expression (mirroring what the JDT does), so we want addExpressions not addConditions.  The datagen looks right, so everywhere else needs to mirror that.
