### ISSUE TITLE
RevisionKeys

### ISSUE THREAD

**Issue by hyjorc1** [boalang/compiler#248]
https://github.com/boalang/compiler/blob/6fa5d2fdc7a133b20677529ad3439fb9c3facca2/src/java/boa/datagen/SeqRepoImporter.java#L264-L287

I am working on the BoaGenerator and trying to slim down the generated dataset size on another branch. 

The code snippet shows that if the size of the `project` w/ commits less than the max size, then the `project` will be written into project.seq file. Else, the `commit`s will be split out of the `project` and stored into commit.seq file.

1. Why do we choose the value of `MAX_SIZE_FOR_PROJECT_WITH_COMMITS` to be `Integer.MAX_VALUE / 3`? 

2. For the revision keys, can we use consecutive integers such as 1, 2, 3, 4,... as revision keys instead of a list of accumlated size values of `commit`s? If this is the case, we only need to store one maximum key value in protobufs `optional int64` instead of a list of keys `repeated int64`.

**Comment by nguyenhoan** [comment]
1. If I remember correctly, when loading a protbuf message, it prepare a buffer whose size is 3 times the size of the message. So that max size tries to prevent the overflow exception.

2. I am not sure I understand the proposal. Can you elaborate on how to use your proposed keys to access the commits in commit.seq file?

**Comment by hyjorc1** [comment]
https://github.com/boalang/compiler/blob/6fa5d2fdc7a133b20677529ad3439fb9c3facca2/src/java/boa/datagen/DefaultProperties.java#L28-L29

https://github.com/boalang/compiler/blob/6fa5d2fdc7a133b20677529ad3439fb9c3facca2/src/java/boa/datagen/scm/GitConnector.java#L169-L181

1. The propety `MAX_COMMITS ` is used to trigger storing `RevisionKeys` or `Revision`s into `CodeRepository`. And the property `MAX_SIZE_FOR_PROJECT_WITH_COMMITS` which is used to trigger splitting `Commit`s out of `Porject` or not. Are you saying both of them are used to prevent the overflow exception?

2. If commit size of one project has exceeded the `MAX_COMMITS`, we will store `RevisionKeys` as a list into `CodeRepository`. Those keys depend on `commitWriterLen`, accumulated size values `[r1.size, r1.size + r2.size, r1.size + r2.size + r3.size, ... ,r1.size + ... + rn.size]`. What I am proposing is that we can use `[1,2,3, ... , n]` as keys and only store an integer `n`, similar to idea of generator in Python.

**Comment by nguyenhoan** [comment]
1. Yes, both of them are being used but MAX_COMMITS would supersede the other.

2. I don't know about how it works with Python dataset. Where are you storing n? Keep in mind that the key in sequence file must be unique so you should not have 2 different files from 2 different projects with same key 1.

**Comment by hyjorc1** [comment]
2. The [generator](https://www.programiz.com/python-programming/generator) is a programming language feature, iterate over a list by generating the each list element in constant space without keeping the whole list, in Python. In datagen, I was thinking if we can use consectutive integers as keys for all revisions of all projects and only store a pair `(n1, n2)` for `RevisionKey`'s range in each `CodeRepository`. If we need those keys for `Revision` retrieval, we can generate that list of keys as `[n1, n1 + 1, n1 + 2, ... , n2]`.

**Comment by psybers** [comment]
Uniqueness for a given project's commit ids is easy.

So why not use a multi-key?  Each key is a pair `(p, c)` where p is a unique id for project, and c is the project's unique commit id.

**Comment by nguyenhoan** [comment]
@hyjorc1 yes, it's possible. Just keep in mind that data is generated in parallel, so make sure key is unique.

@psybers are p and c strings that will be concatenated or 2 int32's that will be combined into a int64? strings would take a lot of space and int32 might not be enough for all projects ids.

**Comment by psybers** [comment]
It can be a custom `Writable` type that contains 2 `VIntWritable` fields.
