### ISSUE TITLE
format() is possibly truncating data

### ISSUE THREAD

**Issue by psybers** [boalang/compiler#35]
From the user list: http://boa.cs.iastate.edu/forum.php?place=msg%2Fboa-user%2F2URws5oQKnk%2FnLkWQnp9EwAJ

"I've been having an issue with output from format() in [this script](http://boa.cs.iastate.edu/boa/index.php?q=boa/job/public/30188) (line 36). For 1320366/1323627 lines of output, a double quote is inserted at the end using this format. However, for 3261 lines (0.2% of the output), this final quote is omitted; this isn't simply a newline appearing in the line, and thus the output continues on the next." To demonstrate, one line of surrounding output is given. Note the end of the middle line (it is truncated):

````
analyst1001/OpenRefine-Hbase,f0ba42f355c8229df4300076926ab9fcfb432831,1270772594000000,"make sure to check the tests as well\n\n\ngit-svn-id: http://google-refine.googlecode.com/svn/trunk@431 7d457c2a-affb-35e4-300a-418c747d4874\n"
analyst1001/OpenRefine-Hbase,16a2600a49493a5befa2d86cd8c6f897238efc1e,1270774844000000,"now it's jslint time to be happier: (!
analyst1001/OpenRefine-Hbase,cc2209074b75892e6cc6d747e97c986d9f793bfa,1270775673000000,"more jslint goodness\n\n\ngit-svn id: http://google-refine.googlecode.com/svn/trunk@433 7d457c2a-affb-35e4-300a-418c747d4874\n" 
````

The commit being truncated: https://github.com/analyst1001/OpenRefine-Hbase/commit/16a2600a49493a5befa2d86cd8c6f897238efc1e

**Comment by eddieantonio** [comment]
My bug, not Boa's... :weary:
