### ISSUE TITLE
Adding kind for finally

### ISSUE THREAD

**Issue by nguyenhoan** [boalang/compiler#36]
Adding kind for finally block statement

**Comment by psybers** [comment]
Does there need to be a *kind* for finally?  Or rather should the TRY statement have an optional attribute 'finally' of type Statement?  Note that the JDT types do not have a specific type for finally clauses, it is a normal BlockStatement.

**Comment by nguyenhoan** [comment]
finally block has a special semantic different from catch clauses.
I think there need to be a kind for it to distinguish it from catch clauses.

**Comment by nguyenhoan** [comment]
ae7af0c1a3f479cff53d2e03d0f078fa336ede77

**Comment by nguyenhoan** [comment]
fix bug: redundant visit
https://github.com/boalang/compiler/commit/13f8c0adedb617e4d6cb6d849e79c4ddafc8d9c3
