### ISSUE TITLE
Resolve types in data generation

### ISSUE THREAD

**Issue by psybers** [boalang/compiler#60]
Currently we only parse source files and provide the parse tree (as a custom AST).  We should also provide resolved types, where possible, and a list of probable resolved types in other cases where we are not certain.

**Comment by nguyenhoan** [comment]
To resolve types in Java, we would parse all source (and class/jar) files in the project instead of single files.

How are we going about the language versions of files?

I am thinking of:
- one pass of parsing single files to get language version
- another pass using the highest version to parse all files to build Boa ast with types

**Comment by psybers** [comment]
There isn't a way to avoid parsing every file twice? Why does the language version matter for this task?

**Comment by nguyenhoan** [comment]
If we tried to parse every file once then it matter because we will only have language version for the entire project.

If we parse twice then each parsing will do a separate task.

I cannot think of anyway to avoid parsing twice.

**Comment by psybers** [comment]
But why do we need the language version for the project?  In reality, a single repo might actually contain multiple language versions.

**Comment by nguyenhoan** [comment]
No, I didn't mean that.
I just meant that we should not use language version that works for all files as the language version of every single file.

**Comment by nguyenhoan** [comment]
Since we are not resolving types for all snapshots, would it be better to store a head snapshot with types separately?

**Comment by nguyenhoan** [comment]
Code
https://github.com/boalang/compiler/blob/datagen2017/src/java/boa/datagen/scm/AbstractConnector.java#L68

Commits
https://github.com/boalang/compiler/commit/ca964b7f931f735af83dbee65fe8027ad479c259
https://github.com/boalang/compiler/commit/e7b3c5d2fbdd0b18179e0643c0dd20118c5cd694
https://github.com/boalang/compiler/commit/c727eded5a83c8087eb77b0c2daec900ea0e9d1a
https://github.com/boalang/compiler/commit/e3c10c2d9a41acaf19fc3f0926a65a36d6c2d66a
https://github.com/boalang/compiler/commit/e9c490b9c4e13ba488e65eb561eb6b1e9d58f5da
https://github.com/boalang/compiler/commit/5153c4710bf15254138e06e58a1003f10bf1e2fa

**Comment by nguyenhoan** [comment]
Use in-project jar files to resolve types
ef1c86a0c2c369f1d6b420e24c20278a9cd66686
99e08f8ac44b7a6fb3099a5b67e130027324e027
