### ISSUE TITLE
Test cases fail on Windows

### ISSUE THREAD

**Issue by psybers** [boalang/compiler#63]
When the test suite runs on Windows, many tests fail.

This might be a line ending issue?

**Comment by nguyenhoan** [comment]
The line ending is fixed here
4e27de19db7b3f8f2e24472f30b13306c4e02293

**Comment by nguyenhoan** [comment]
This fails on Windows
test:
    [junit] Testsuite: boa.test.compiler.TestCodegenGood
    [junit] Tests run: 21, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 22.125 sec
    [junit] Testcase: knownGood[test\codegen\allowed-stops.boa] took 3.219 sec
    [junit] Testcase: knownGood[test\codegen\array-as-map-key.boa] took 1.105 sec
    [junit] Testcase: knownGood[test\codegen\arrays.boa] took 1.137 sec
    [junit] Testcase: knownGood[test\codegen\def.boa] took 0.96 sec
    [junit] Testcase: knownGood[test\codegen\func-returns-int.boa] took 0.942 sec
    [junit] Testcase: knownGood[test\codegen\function-as-arg.boa] took 0.253 sec
    [junit] 	FAILED
    [junit] found unexpected exception: Error on line 151: ')' expected
    [junit] junit.framework.AssertionFailedError: found unexpected exception: Error on line 151: ')' expected
    [junit] 	at boa.test.compiler.BaseTest.codegen(BaseTest.java:309)
    [junit] 	at boa.test.compiler.BaseTest.codegen(BaseTest.java:242)
    [junit] 	at boa.test.compiler.TestCodegenGood.knownGood(TestCodegenGood.java:54)
    [junit] Testcase: knownGood[test\codegen\function-calls.boa] took 0.91 sec
    [junit] Testcase: knownGood[test\codegen\function-many-args.boa] took 0.942 sec
    [junit] Testcase: knownGood[test\codegen\issue87.boa] took 0.928 sec
    [junit] Testcase: knownGood[test\codegen\map-int-index.boa] took 0.941 sec
    [junit] Testcase: knownGood[test\codegen\maps.boa] took 0.95 sec
    [junit] Testcase: knownGood[test\codegen\nested-func.boa] took 0.954 sec
    [junit] Testcase: knownGood[test\codegen\nested-maps.boa] took 1.198 sec
    [junit] Testcase: knownGood[test\codegen\no-weight.boa] took 0.935 sec
    [junit] Testcase: knownGood[test\codegen\proto-as-mapkey.boa] took 0.914 sec
    [junit] Testcase: knownGood[test\codegen\select-from-func-return.boa] took 0.924 sec
    [junit] Testcase: knownGood[test\codegen\sets.boa] took 0.937 sec
    [junit] Testcase: knownGood[test\codegen\stacks.boa] took 0.915 sec
    [junit] Testcase: knownGood[test\codegen\sum-double.boa] took 0.903 sec
    [junit] Testcase: knownGood[test\codegen\tuple.boa] took 0.991 sec
    [junit] Testcase: knownGood[test\codegen\while.boa] took 1.058 sec
    [junit] Test boa.test.compiler.TestCodegenGood FAILED
    [junit] Testsuite: boa.test.compiler.TestGood

**Comment by psybers** [comment]
This can't currently be reproduced. Closing.
