### ISSUE TITLE
Add Git tags to datasets

### ISSUE THREAD

**Issue by psybers** [boalang/compiler#73]
Git supports tagging commits.  We need to keep this data (list of tags and their associated commit hashes) in our dataset.

Our code currently has a getTags() for Git, but it is never called anywhere.  See:
https://github.com/boalang/compiler/blob/32521c55d1dbcbbb8ca759eb5fc4c443530c586c/src/java/boa/datagen/scm/GitConnector.java#L123

**Comment by nguyenhoan** [comment]
https://github.com/boalang/compiler/commit/a873dfabc22418a745ca3d4c6d93f2f1fa4454c6
