### ISSUE TITLE
Unable To Build: Cannot run program "protoc"

### ISSUE THREAD

**Issue by adamhammes** [boalang/compiler#86]
I pulled down the current branch master and tried to build the project, resulting in the following error in both Eclipse and Intellij:

```
/Users/hammesa/dev/compiler/build.xml:80: Execute failed: java.io.IOException: 
Cannot run program "protoc": error=2, No such file or directory
```

When I run `protoc --version` from my terminal, I get the following output:

```
libprotoc 2.5.0
```

indicating that `protoc` is both installed and in my PATH.

I am running OS X El Capitan, version 10.11.16.

**Comment by psybers** [comment]
What happens if you run ````which protoc```` from terminal?

**Comment by adamhammes** [comment]
```
$ which protoc
/usr/local/bin/protoc
```

Hoan also suggested putting the executable in the top-level directory and building, but that resulted in the same error.

Also Hoan rebuilt his project for the first time in "a while" and also had this error.

**Comment by psybers** [comment]
Oh, you are building from an IDE. Almost certainly the IDE has its own custom PATH environment.  If you build directly from command line with ````ant``` does it work?

**Comment by adamhammes** [comment]
Ah, yes it does. I'll figure out how to the get the IDE to work.
