### ISSUE TITLE
Error in Code generation for looping over primitive type

### ISSUE THREAD

**Issue by nmtiwari** [boalang/compiler#88]
userFunction := function(vals: array of int) : int {
    total : int = 0;
    foreach(i : int; def(vals[i])) {
        total = total + vals[i];
    }
    return total;
};

Code generation of above written code is as follows: 

					@Override
					public Long invoke(final long[] ___vals) throws Exception
					{
						___total = 0l;
						for (long ___i = 0; ___i < ___vals.length; ___i++)
						{
							if ((___vals[(int)(___i)] != null))
							{
								{
									___total = ___total + ___vals[(int)(___i)];
								}
							}
						}

						return ___total;
					}

**Comment by psybers** [comment]
I can not confirm this bug on the master branch.

The sample code provided compiles without error.
